### ISSUE TITLE
Dedicar Ram

### ISSUE THREAD

**Issue by cisplays** [zkingboos/mc-dripcraft-server#1]
Não é bem um problema, mas mais uma questão.
Como posso dedicar mais ram ao servidor?

**Comment by zkingboos** [comment]
Olá, primeiramente desculpa pela demora para responder a sua issue. 
Para poder alocar mais ram no servidor você deve ir em `server-setup-config.yaml` e mudar a seção `launch.maxRam` para a quantidade desejada!
Ex: 10G (10 * 1024)
