### ISSUE TITLE
Server has been stopped

### ISSUE THREAD

**Issue by LucasAraujo2409** [zkingboos/mc-dripcraft-server#2]
Boa tarde, estou tentando abrir o server de dripcraft só que o server para sozinho, segue print do que acontece. (baixei aqui do github e la do curse forge, só que nenhum dos 2 deu certo)
![image](https://user-images.githubusercontent.com/65241332/145687200-9eb392aa-5912-440b-99f2-3d9df23da72d.png)

**Comment by zkingboos** [comment]
Olá, você poderia postar o erro completo?

**Comment by LucasAraujo2409** [comment]
Então, eu tinha conseguido fazer ir só que eu não lembro o que eu fiz e agora ele não está indo de novo, só que agora ele só fecha totalmente. Tem alguma ideia do que pode ser? Será que pode ser porque eu tirei o dungon gears?

**Comment by LucasAraujo2409** [comment]
Será que eu preciso de alguma versão específica do java jdk?

**Comment by zkingboos** [comment]
> Então, eu tinha conseguido fazer ir só que eu não lembro o que eu fiz e agora ele não está indo de novo, só que agora ele só fecha totalmente. Tem alguma ideia do que pode ser? Será que pode ser porque eu tirei o dungon gears?

Não acho que seja por causa disso. Precisaria ver os logs pra ter certeza do que é.

> Será que eu preciso de alguma versão específica do java jdk?

Sim, nas versões do Minecraft 1.16> precisam da versão 11 do java.

**Comment by LucasAraujo2409** [comment]
> > Então, eu tinha conseguido fazer ir só que eu não lembro o que eu fiz e agora ele não está indo de novo, só que agora ele só fecha totalmente. Tem alguma ideia do que pode ser? Será que pode ser porque eu tirei o dungon gears?
> 
> Não acho que seja por causa disso. Precisaria ver os logs pra ter certeza do que é.
> 
> > Será que eu preciso de alguma versão específica do java jdk?
> 
> Sim, nas versões do Minecraft 1.16> precisam da versão 11 do java.

Eu estou com o jdk 11

**Comment by LucasAraujo2409** [comment]
Consegui arrumar, acho que os arquivos estavam corrompidos só, eu reinstalei o server e deu tudo certo, obrigado e desculpa o incomodo.
